Fixed: compiling jsc on mavericks
Previously, for all os x versions, gcc was being used but mavericks uses
new objective-c syntax that can't be built by gcc (at least with version
that comes with xcode) and produced following error:

/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:16:
error: expected ‘,’ or ‘}’ before ‘__attribute__’

Now, Makefile can detect Mavericks and will use clang for it.

Fixes cappuccino/cappuccino#2022